export const getPopoverStyles = (statusCategoryType: string) => ({
    modalBody: {
        position: 'relative' as 'relative',
        width: '380px',
        height: '500px',
        margin: '100px auto',
        filter: 'drop-shadow(0px 12px 32px rgba(0, 0, 0, 0.12))',
        backgroundColor: 'black',

    },
    container: {
        display: 'flex',
        maxWidth:380,
        flexDirection: 'column' as 'column',
        alignItems: 'center',
        position: 'absolute' as 'absolute',
        left: 0,
        right: 0,
        top: 'calc(50% - 311px/2)',
        background: '#FFFFFF',
        border: '1px solid rgba(63, 67, 80, 0.16)',
        borderRadius: '4px',
    },
    header: {
        display: 'flex',

        flexDirection: 'row' as 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '10px 24px 12px',
        position: 'static' as 'static',
        width: '90%',
        height: '20px',
        flex: 'none',
        order: '0',
        alignSelf: 'stretch',
        flexGrow: '0',
        margin: '0px 0px',
    },

    appAvatar: {
        background: 'black',
        position: 'absolute' as 'absolute',
        left: "90%",
        width: '18px',
        height: '18px',
        top: '14px',
        borderRadius: 50,
        mixBlendMode: 'normal' as 'normal',
    },
    ticketName: {
        position: 'static' as 'static',
        width: '90%',
        // height: '16px',
        top: '2px',
        fontFamily: 'Open Sans',
        fontStyle: 'normal',
        fontWeight: 'normal',
        lineHeight: '12px',
        color: 'rgba(63, 67, 80, 0.72)',
        display: 'flex',
        fontSize: '12px',
        alignItems: 'center',
        flex: 'none',
        order: 1,
        flexGrow: 0,
        margin: '0px 6px',
    },
    //
    body: {
        //background:'red',
        display: 'flex',
        flexDirection: 'column' as 'column',
        alignItems: 'flex-start',
        padding: '0px 24px 12px 24px',
        position: 'static' as 'static',
        flex: 'none',
        order: 1,
        alignSelf: 'stretch',
        borderBottom: '1px solid rgba(63, 67, 80, 0.16)',
    },
    bodyFrame: {
        display: 'flex',
        flexDirection: 'column' as 'column',
        alignItems: 'flex-start',
        position: 'static' as 'static',
        width: '332px',
        flex: 'none',
        alignSelf: 'stretch',
    },

    bodyFrameDescription: ({
        textAlign: 'left' as 'left',
        fontFamily: 'Open Sans',
        fontStyle: 'normal',
        overflow: 'hidden' as 'hidden',
        fontWeight: 'normal',
        minHeight: '28px',
        maxHeight: '58px',
    }),

    bodyFrameLabel: {
        display: 'flex',
        flexDirection: 'row' as 'row',
        overflow: 'hidden' as 'hidden',
        //overflow: 'hidden' as 'hidden',
    },
    bodyFrameLabels: {
        flexDirection: 'row' as 'row',
        alignItems: 'center',
        flex: 'none',
        fontFamily: 'Open Sans',
        fontSize: '10px',
        fontStyle: 'normal',
        fontWeight: "600px",
        lineHeight: '16px',
        display: 'flex',
        alignItem: 'center',
        order: 1,
        height:16,
        background: 'rgba(63, 67, 80, 0.08)',
        margin: '5px 5px 5px 0px',
        padding: '0px 8px',
    },
    bodyFrameLabelsTotalHide: {
        textAlign: 'left' as 'left',
        fontSize: '12px',
    },

    footer: {
        display: 'flex',
        padding: "0px 24px",
        flexDirection: 'row' as 'row',
        alignItems: 'center',
        position: 'static' as 'static',
        flex: 'none',
        alignSelf: 'stretch',
        borderTop: '1px solid rgba(63, 67, 80, 0.16)',
        order: 3,
    },

})